# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="example.proto",
    package="",
    syntax="proto3",
    serialized_options=None,
    serialized_pb=b'\n\rexample.proto"\x10\n\x03\x46oo\x12\t\n\x01\x61\x18\x01 \x01(\t"\x10\n\x03\x42\x61r\x12\t\n\x01\x62\x18\x01 \x01(\t2"\n\x07\x45xample\x12\x17\n\x05Hello\x12\x04.Foo\x1a\x04.Bar"\x00\x30\x01\x62\x06proto3',
)


_FOO = _descriptor.Descriptor(
    name="Foo",
    full_name="Foo",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="a",
            full_name="Foo.a",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=17,
    serialized_end=33,
)


_BAR = _descriptor.Descriptor(
    name="Bar",
    full_name="Bar",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="b",
            full_name="Bar.b",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=35,
    serialized_end=51,
)

DESCRIPTOR.message_types_by_name["Foo"] = _FOO
DESCRIPTOR.message_types_by_name["Bar"] = _BAR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Foo = _reflection.GeneratedProtocolMessageType(
    "Foo",
    (_message.Message,),
    {
        "DESCRIPTOR": _FOO,
        "__module__": "example_pb2"
        # @@protoc_insertion_point(class_scope:Foo)
    },
)
_sym_db.RegisterMessage(Foo)

Bar = _reflection.GeneratedProtocolMessageType(
    "Bar",
    (_message.Message,),
    {
        "DESCRIPTOR": _BAR,
        "__module__": "example_pb2"
        # @@protoc_insertion_point(class_scope:Bar)
    },
)
_sym_db.RegisterMessage(Bar)


_EXAMPLE = _descriptor.ServiceDescriptor(
    name="Example",
    full_name="Example",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    serialized_start=53,
    serialized_end=87,
    methods=[
        _descriptor.MethodDescriptor(
            name="Hello",
            full_name="Example.Hello",
            index=0,
            containing_service=None,
            input_type=_FOO,
            output_type=_BAR,
            serialized_options=None,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_EXAMPLE)

DESCRIPTOR.services_by_name["Example"] = _EXAMPLE

# @@protoc_insertion_point(module_scope)
