# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import example_pb2 as example__pb2


class ExampleStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Hello = channel.unary_stream(
            "/Example/Hello",
            request_serializer=example__pb2.Foo.SerializeToString,
            response_deserializer=example__pb2.Bar.FromString,
        )


class ExampleServicer(object):
    """Missing associated documentation comment in .proto file"""

    def Hello(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ExampleServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Hello": grpc.unary_stream_rpc_method_handler(
            servicer.Hello,
            request_deserializer=example__pb2.Foo.FromString,
            response_serializer=example__pb2.Bar.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "Example", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class Example(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def Hello(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/Example/Hello",
            example__pb2.Foo.SerializeToString,
            example__pb2.Bar.FromString,
            options,
            channel_credentials,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
